services:
    frontend:
        build:
            context: frontend
            dockerfile: Dockerfile
        ports:
            - "5173:5173"
        volumes:
            - ./frontend:/app
            - /app/node_modules
        command: bun run dev -- --host
        env_file:
            - .env
        depends_on:
            - backend
            - db

    backend:
        build: 
          context: backend
          dockerfile: Dockerfile
        command: "uvicorn main:app --host 0.0.0.0"
        depends_on:
            - db
        ports:
            - "8000:8000"
        volumes:
            - ./backend:/backend
        env_file:
            - .env

    db:
        image: postgres:16
        volumes:
            - ./db:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin4_container
        restart: always
        ports:
            - "8888:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
        volumes:
            - pgadmin-data:/var/lib/pgadmin

volumes:
    pgadmin-data:
    data:
